# -*- coding: utf-8 -*-
"""TP1-GRUPO-26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TPtbpLvU7TZHx7fK5QtKd-Jlt_MLBXth

## a) Exploración Inicial : analizar cada variable, considerando los siguientes aspectos
- Tipo de variable
- Variables Cuantitativas: calcular medidas de resumen: media, mediana,moda, etc
- Variables Cualitativas: reportar los posibles valores que toman y cuán
frecuentemente lo hacen.
- Determinar si existen variables irrelevantes para el análisis
- Realizar un análisis gráfico de las distribuciones de las variables
- Analizar las correlaciones existentes entre las variables.
- Analizar la relación de las variables con el target



Es un problema de clasificacion binaria, se cancela o no se cancela

# Checkpoint 1:

## Variable / tipo:

 0.   hotel                           /string

 1.   lead_time                       /int64  
 
 2.   arrival_date_year               /int64

 3.   arrival_date_month              /object 

 4.   arrival_date_week_number        /int64

 5.   arrival_date_day_of_month       /int64  

 6.   stays_in_weekend_nights         /int64  

 7.   stays_in_week_nights            /int64  

 8.   adults                          /int64  

 9.  children                        /float64

 10.  babies                          /int64  

 11.  meal                            /object 

 12.  country                         /object 

 13.  market_segment                  /object 

 14.  distribution_channel            /object 

 15.  is_repeated_guest               /int64  

 16.  previous_cancellations          /int64  

 17.  previous_bookings_not_canceled  /int64  

 18.  reserved_room_type              /object 

 19.  assigned_room_type              /object 

 20.  booking_changes                 /int64  

 21.  deposit_type                    /object 

 22.  agent                           /float64

 23.  company                         /float64

 24.  days_in_waiting_list            /int64  

 25.  customer_type                   /object 

 26.  adr                             /float64

 27.  required_car_parking_spaces     /int64  

 28.  total_of_special_requests       /int64  

 29.  reservation_status              /object 

 30.  reservation_status_date         /object 

 31.  id                              /object 

 32.  is_canceled                     /int64 "preguntado en clase, segun el profe es un depende, pero apuntó que esta variable es cualitativa"

# **Descripcion de los campos**

*   hotel: Nombre del hotel
*   lead_time: El tiempo que se mide desde que el huesped hace una reserva hasta que llega a hospedarse
*   arrival_date_year: El año en el que se hospeda

*   arrival_date_month: El mes en el que se hospeda

*   arrival_date_week_number: El dia de la semana en el que se hospeda

*  arrival_date_day_of_month: El dia del mes en el que se hospeda  

*  stays_in_weekend_nights: La cantidad de noches que se hospeda en el fin de semana

*  stays_in_week_nights: La cantidad de noches que se hospeda en los dias de semana 

*  adults: La cantidad de adultos que se hospedan

*  children: La cantidad de menores que se hospedan

*  babies: La cantidad de bebes que se hospedan

*  meal: El plan de comidas que se reservo, 
  * BB: Solo desayuno
  * HB: Desayuno y cena
  * FB: Desayuno, almuerzo y cena
  * SC: Ninguna comida, solo catering
  * Undefined: Indefinido

*  country: Codigo de tres letras que representan un país

*  market_segment: Es una manera de segmentar por caracteristicas al grupo que se hospeda: Online TA es online travel agent, etc.

*   distribution_channel: Es el metodo o plataforma por el cual el hotel vende los cuartos

*   is_repeated_guest: Indica si la persona ya se ha hospedado en el hotel
  * 1=Si
  * 0=No 

*  previous_cancellations: La cantidad de veces que han cancelado la reserva de un cuarto

*  previous_bookings_not_canceled: La cantidad de veces que no han cancelado la reserva de un cuarto

*   reserved_room_type: El tipo de cuarto, se indica con una letra

*    assigned_room_type: El cuarto asignado

*    booking_changes: La cantidad de cambios que se le hicieron a la fecha de hospedaje  

*    deposit_type: El tipo de deposito 

*   agent: codigo para los agentes que se encargan de reservar

*   company: codigo para las empresas que se encargan de reservar

*    days_in_waiting_list: Dias que pasa el cliente en la lista de espera 

*    customer_type: Tipo de huesped, transitorio, grupo, contractual, etc.

*    adr: Tarifa media diaria de una habitación durante un periodo determinado 

*    required_car_parking_spaces: La cantidad de lugares de estacionamiento solicitados  

*    total_of_special_requests: La cantidad de solicitudes especiales que se hicieron por parte del huesped  

*    reservation_status: El estado de la reserva, check out, cancelado, sin aparecer.

*    reservation_status_date: Fecha de un estado (?)

*    id: Codigo de registro del movimiento

*    is_canceled: Indica si se cancela la reserva
  * 1=Si 
  * 0=No

## Variables cuantitativas:

### lead_time

mean       112.2

std        110.7

min          0.0

25%         23.0

50%         78.0

75%        172.0

max        629.0

----------------


### adults

count 61913.0

mean      1.9

std       0.6

min       0.0

25%       2.0

50%       2.0

75%       2.0

max      55.0

----------------

 ### children

count   61909.0

mean        0.1

std         0.4

min         0.0

25%         0.0

50%         0.0

75%         0.0

max        10.0

----------------

 ### babies

count 61913.0

mean      0.0

std       0.1

min       0.0

25%       0.0

50%       0.0

75%       0.0

max       9.0

----------------

### days_in_waiting_list
count               61913.0

mean                    2.6


std                    18.6

min                     0.0


25%                     0.0

50%                     0.0

75%                     0.0

max                   391.0

----------------


### adr
count 61913.0

mean    102.4

std      47.8

min      -6.4

25%      70.0

50%      95.0

75%     126.0

max     510.0



----------------

### total_of_special_requests
count                    61913.0
mean                         0.5
std                          0.8
min                          0.0
25%                          0.0
50%                          0.0
75%                          1.0
max                          5.0

## Variables consideradas no relevantes para el analisis:


*   id
*   reservation_status
*   reservation_status_date

## Set up para graficar y usar pandas.
"""

import pandas as pd
from IPython.display import display
import datetime

direc = "https://raw.githubusercontent.com/Akselas/7506R-1C2023-GRUPO26/main/hotels_train.csv"

df = pd.read_csv(direc)
pd.set_option('display.float_format', lambda x: '%.1f' % x)

"""## Reconocimiento basico de las variables"""

#Variables y sus tipos:
df.info(show_counts= False) #esto lo muestra enumerado
print(df.dtypes) #esto lo muestra sin numeracion

#Variables cuantitativas:
#print(df.describe())
columnas = df.columns
for col in columnas:
  print(df[[col]].describe())

print(df["adr"].value_counts())

df["is_repeated_guest"].value_counts()

df["is_canceled"].value_counts()

df["is_repeated_guest"].value_counts()

df["agent"].value_counts(dropna=False)

df["arrival_date_month"].value_counts()

df["babies"].mode()

df["days_in_waiting_list"].value_counts()

df["lead_time"].mode()

df["previous_cancellations"].value_counts()

print(df["reserved_room_type"].value_counts())

print(df["hotel"].value_counts(dropna=False))

print(df["company"].value_counts(dropna=False))

print(df["booking_changes"].value_counts())

print(df["distribution_channel"].value_counts())

print(df["market_segment"].value_counts())

df["meal"].mode()
df["meal"].value_counts()

print(df["is_repeated_guest"].value_counts())

print(df["customer_type"].value_counts())

print(df["reservation_status"].value_counts())

print(df["reservation_status_date"].value_counts())

print(df["id"].value_counts())

df["country"].value_counts()

df["deposit_type"].value_counts()

"""# Visualizacion de los datos

## Distribucion de variables:
"""

import seaborn as sns
from matplotlib import pyplot as plt

#country, solo el top 10 de paises con mas reservas
df_relevant_countries = df.copy()
n=10
paises_no_relevantes = df["country"].value_counts().index.tolist()[(n-149):]

for pais in paises_no_relevantes:
  df_relevant_countries.drop(df[df["country"] == pais].index, axis='index', inplace=True)

ax = sns.countplot(x='country',data=df_relevant_countries)
ax.bar_label(ax.containers[0])
plt.show()

#hotel
ax = sns.countplot(x='hotel', data=df)
sns.countplot(x='hotel', data=df).set(title="Distribucion de reservas en hoteles")
ax.bar_label(ax.containers[0])
plt.show()

#adults y children

sns.scatterplot(data=df, x='adults', y='children', hue="is_canceled").set(title="Cantidad de adultos que reservan junto a niños")
reserva_sin_adultos = df[df["adults"]==0]
len(reserva_sin_adultos)
#podemos ver que hay 197 reservas en las cuales no hay adultos.
#podemos ver que la mayoria de adultos no reserva con niños.

#days_in_waiting_list y lead_time
sns.scatterplot(x="days_in_waiting_list",y="lead_time",data=df, hue="is_canceled").set(title="Dias en la lista de espera y tiempo entre reserva y check-in")

#deposit_types

sns.countplot(x="deposit_type",data=df).set(title="Distribucion de reservas por tipo de deposito")
ax= sns.countplot(x="deposit_type",data=df)
ax.bar_label(ax.containers[0])

#meal
sns.countplot(x="meal",data=df).set(title="Distribucion de reservas por plan de comida que se contrata")

#agent, top 10 agents con mas reservas
df_relevant_agents = df.copy()
n=10
agent_no_relevantes = df["agent"].value_counts().index.tolist()[(n-297):]

for agent in agent_no_relevantes:
  df_relevant_agents.drop(df[df["agent"] == agent].index, axis='index', inplace=True)

ax = sns.countplot(x='agent',data=df_relevant_agents)
ax.bar_label(ax.containers[0])
plt.show()

#is_repeated_guest
sns.countplot(data=df, x="is_repeated_guest", hue="is_canceled").set(title="Distribucion de las reservas de personas que ya se han hospedado en ese hotel")
plt.show()

"""## Relaciones de variables"""

import seaborn as sns
import matplotlib.pyplot as plt

# Scatter plot amount of booking_changes and cancelations
sns.scatterplot(data=df, x='booking_changes', y='is_canceled')

# Set the plot title and axis labels
plt.title('Relacion entre Cantidad de cambios de booking y Cancelaciones')
plt.xlabel('Number of number of Booking Changes')
plt.ylabel('Is Canceled')

# Show the plot
plt.show()

# Create a countplot of arrival_date_year with is_canceled as the hue
sns.countplot(data=df, x='arrival_date_year', hue='is_canceled')

# Set the plot title and axis labels
plt.title('Cancelacion por año de reserva')
plt.xlabel('Year of Reservation')
plt.ylabel('Count')

# Show the plot
plt.show()

plt.title('Cancelacion por tipo de deposito')
plt.xlabel('Tipo de deposito')

sns.countplot(data=df, x='deposit_type', hue='is_canceled')
plt.show()

sns.countplot(data=df, x='required_car_parking_spaces', hue='is_canceled').set(title="Distribucion de la cantidad de espacios de estacionamientos que se reservan y su relacion con la cancelacion")
plt.show()

#busco outliers
outlier = df[df["adults"]>4]
#outlier["is_canceled"].mean()
#print(outlier)
outlier["is_canceled"]
#todas las reservas de mas de 4 adultos cancelaron
#sns.relplot(data=df, y='adults',x='is_canceled',palette=["r","g"])

var_cancel = df["is_canceled"]
var_days = df["arrival_date_month"]

tabla=pd.crosstab(var_days, var_cancel)
sns.heatmap(tabla, annot=True)

#Grafico relplot para buscar relaciones
ds_sca = df.copy()
sns.scatterplot(y='children', x='adults',hue="meal",data=ds_sca).set(title= "Disperso de adultos con niños distinguidos por que plan de comidas reservan",xlabel= 'Estado 0 = No es repetido, 1 = Es repetido', ylabel= 'Cant. de cancelaciones previas')
plt.show()

sns_boxplot = sns.relplot(data=df, x="days_in_waiting_list",y="booking_changes",hue="is_canceled",palette=["r", "g"]).set(title="Dias en lista de espera vs cambios en la reserva",xlabel='Dias',ylabel='Cambios')

sns_boxplot = sns.boxplot(x='is_canceled',y='lead_time',data=df).set(title="Boxplot de la relacion entre el tiempo de  reserva y la cancelacion",xlabel= "No cancelado: 0, Cancelado:1",ylabel="Tiempo de reserva")

sns_boxplot = sns.boxplot(x='is_canceled',y='adr',data=df).set(title="Boxplot ADR vs la cancelacion",xlabel= "No cancelado: 0, Cancelado:1",ylabel="ADR")

#Gráfico de relacion pairplot de la variable "is_canceled" en funcion de las variables que considero importante
#dejo el link a la imagen para que no tengas que correrlo de vuelta porque el collab se demoró 
#como 6 minutos en hacerme el grafico xD

columns=df.columns.tolist()
lista_de_cosas_por_remover = ['meal','country','market_segment','distribution_channel','reserved_room_type','assigned_room_type','deposit_type','agent','company','customer_type','adr','required_car_parking_spaces','reservation_status','reservation_status_date','id','babies','children','adults','stays_in_weekend_nights','arrival_date_day_of_month','arrival_date_week_number','arrival_date_month','arrival_date_year','hotel']
for col in lista_de_cosas_por_remover:
  columns.remove(col)
ds_pairplot=df[columns].copy()
graf_pairplot=sns.pairplot(data=ds_pairplot, hue="is_canceled", palette=["r", "g"])

"""Relacion de is_canceled con las otras variables, para que no la tengas que graficar de vuelta y para verla en mejor detalle la subí acá:
https://raw.githubusercontent.com/Akselas/7506R-1C2023-GRUPO26/main/relacion_is_canceled.png

# Datos faltantes
"""

#tomo las reservas que no tienen adultos,ni niños, ni bebes
#las considero como outliers
df_hotel_sin_personas = df[(df['children'] == 0) & (df['babies'] == 0) &(df['adults'] == 0)]
len(df_hotel_sin_personas)
sns.countplot(data=df_hotel_sin_personas, x='is_canceled')
plt.title('Cancelacion de reservas para ninguna persona')

print(df["company"].value_counts(dropna=False))
#hay 58761 reservas que no especifican la compañia, puede que sea un dato irrelevante igual.

reserva_gratis = df[df["adr"]<=0]
len(reserva_gratis)